# Generated by Django 3.2.5 on 2022-03-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0006_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Overall_grade',
            field=models.CharField(blank=True, default='A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='all_stu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='result',
            field=models.CharField(blank=True, default='Qualified', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='stu_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub1_grade',
            field=models.CharField(blank=True, default='A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub1_marks',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub1_obtained',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub1_remaks',
            field=models.CharField(blank=True, default='Very Good', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub2_grade',
            field=models.CharField(blank=True, default='A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub2_marks',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub2_obtained',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub2_remaks',
            field=models.CharField(blank=True, default='Very Good', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub3_grade',
            field=models.CharField(blank=True, default='A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub3_marks',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub3_obtained',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub3_remaks',
            field=models.CharField(blank=True, default='Very Good', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub4_grade',
            field=models.CharField(blank=True, default='A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub4_marks',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub4_obtained',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub4_remaks',
            field=models.CharField(blank=True, default='Very Good', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub5_grade',
            field=models.CharField(blank=True, default='A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub5_marks',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub5_obtained',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub5_remaks',
            field=models.CharField(blank=True, default='Very Good', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='teacher_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_marks',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_obtained',
            field=models.IntegerField(blank=True, default=800, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
